// SPDX-License-Identifier: GPL-3.0-or-later
//! Client (net-slave) config generation. Produces an apcupsd.conf for a
//! machine that draws power from one of this host's UPSes but runs apcupsd in
//! network-client mode, plus a deploy bundle (config + install instructions).

use crate::config::ConfigFile;

#[derive(Debug, Clone)]
pub struct ClientParams {
    /// Master NIS endpoint, e.g. "192.168.1.10:3551".
    pub master_addr: String,
    /// UPS name (cosmetic on the client; matches the master's UPSNAME).
    pub ups_name: String,
    /// Client shuts down at/below this battery %. Should be >= master's.
    pub battery_level: i64,
    /// Client shuts down at/below this runtime (min). Should be >= master's.
    pub minutes: i64,
    /// Seconds between polls of the master.
    pub polltime: i64,
}

impl Default for ClientParams {
    fn default() -> Self {
        // Conservative defaults: client shuts down before the master cuts power.
        ClientParams {
            master_addr: String::new(),
            ups_name: String::new(),
            battery_level: 15,
            minutes: 8,
            polltime: 10,
        }
    }
}

/// Suggest client params from the master's parsed config, bumping thresholds
/// so the client always shuts down before the master.
pub fn suggest_from_master(master: &ConfigFile, master_addr: &str) -> ClientParams {
    let name = master.get("UPSNAME").unwrap_or("ups").to_string();
    let m_batt = master.get("BATTERYLEVEL").and_then(|v| v.trim().parse().ok()).unwrap_or(5);
    let m_min = master.get("MINUTES").and_then(|v| v.trim().parse().ok()).unwrap_or(3);
    ClientParams {
        master_addr: master_addr.to_string(),
        ups_name: name,
        // 5 points / 3 minutes of head start, clamped to sane bounds.
        battery_level: (m_batt + 5).clamp(0, 100),
        minutes: (m_min + 3).clamp(0, 1440),
        polltime: 10,
    }
}

pub fn render_conf(p: &ClientParams) -> String {
    format!(
        "## apcupsd CLIENT config - generated by apctui\n\
         ## Deploy on a machine powered by '{name}' but not directly attached.\n\
         ##\n\
         ## Ordering: a client must finish shutting down BEFORE the master cuts\n\
         ## UPS power, so these thresholds are deliberately more conservative\n\
         ## than the master's.\n\
         \n\
         UPSNAME {name}\n\
         UPSCABLE ether\n\
         UPSTYPE net\n\
         DEVICE {addr}\n\
         POLLTIME {poll}\n\
         \n\
         BATTERYLEVEL {batt}\n\
         MINUTES {min}\n\
         TIMEOUT 0\n\
         \n\
         # a client does not serve NIS itself\n\
         NETSERVER off\n\
         \n\
         LOCKFILE /var/lock\n\
         SCRIPTDIR /etc/apcupsd\n\
         PWRFAILDIR /etc/apcupsd\n\
         NOLOGINDIR /etc\n",
        name = p.ups_name,
        addr = p.master_addr,
        poll = p.polltime,
        batt = p.battery_level,
        min = p.minutes,
    )
}

/// A deploy bundle: the conf plus a short README with copy-paste install steps.
pub fn render_bundle_readme(p: &ClientParams) -> String {
    let port = p.master_addr.split_once(':').map(|x| x.1).unwrap_or("3551");
    format!(
        "apcupsd network client for '{name}'\n\
         =====================================\n\
         \n\
         This machine will monitor the UPS '{name}' served by {addr} and shut\n\
         itself down on low battery, before the master host powers off.\n\
         \n\
         Install (Debian/Ubuntu):\n\
         \n\
         1. Install apcupsd:\n\
         \n\
              sudo apt update && sudo apt install -y apcupsd\n\
         \n\
         2. Replace the config:\n\
         \n\
              sudo cp apcupsd.conf /etc/apcupsd/apcupsd.conf\n\
         \n\
         3. Enable startup (some distros gate this):\n\
         \n\
              sudo sed -i 's/^ISCONFIGURED=.*/ISCONFIGURED=yes/' /etc/default/apcupsd 2>/dev/null || true\n\
         \n\
         4. Start it:\n\
         \n\
              sudo systemctl enable --now apcupsd\n\
         \n\
         5. Verify it can reach the master:\n\
         \n\
              apcaccess status {addr}\n\
         \n\
         Firewall note: the master must allow inbound TCP on its NIS port from\n\
         this client's IP. On the master:\n\
         \n\
              sudo ufw allow from <this-client-ip> to any port {port} proto tcp\n\
         \n\
         The NIS protocol is unauthenticated and read-only; scope it to trusted\n\
         hosts with your firewall.\n",
        name = p.ups_name,
        addr = p.master_addr,
        port = port,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conf_has_required_net_directives() {
        let p = ClientParams {
            master_addr: "10.0.0.1:3551".into(),
            ups_name: "rack-main".into(),
            ..Default::default()
        };
        let conf = render_conf(&p);
        assert!(conf.contains("UPSTYPE net"));
        assert!(conf.contains("UPSCABLE ether"));
        assert!(conf.contains("DEVICE 10.0.0.1:3551"));
        assert!(conf.contains("NETSERVER off"));
    }

    #[test]
    fn generated_conf_validates_clean() {
        let p = ClientParams {
            master_addr: "10.0.0.1:3551".into(),
            ups_name: "rack-main".into(),
            ..Default::default()
        };
        let cf = ConfigFile::parse(&render_conf(&p));
        let findings = crate::config::validate(&cf);
        assert!(!crate::config::validate::has_errors(&findings), "{findings:?}");
    }

    #[test]
    fn suggest_bumps_thresholds_above_master() {
        let master = ConfigFile::parse("UPSNAME m\nBATTERYLEVEL 10\nMINUTES 5\n");
        let p = suggest_from_master(&master, "10.0.0.1:3551");
        assert!(p.battery_level > 10);
        assert!(p.minutes > 5);
        assert_eq!(p.ups_name, "m");
    }
}
